export const SEL = {
	login: {
		email: 'login-email',
		password: 'login-password',
		submit: 'login-submit',
		error: 'login-error',
	},
	nav: {
		sale: 'nav-sale',
		adminToggle: 'nav-admin-toggle',
		adminUsers: 'nav-admin-users',
		adminPlaces: 'nav-admin-places',
		adminGoods: 'nav-admin-goods',
		adminCurrencies: 'nav-admin-currencies',
		adminTransactions: 'nav-admin-transactions',
		adminCharge: 'nav-admin-charge',
		adminGroups: 'nav-admin-groups',
		checkIn: 'nav-check-in',
		cardInfo: 'nav-card-info',
		logout: 'nav-logout',
		debugToggle: 'nav-debug-toggle',
	},
	topMenu: {
		balance: 'top-menu-balance',
		place: 'top-menu-place',
		toggle: 'top-menu-toggle',
	},
	cardLoader: {
		userSelect: 'card-loader-debug-user-select',
		newCard: 'card-loader-debug-new-card',
	},
	form: {
		submit: 'form-submit',
		cancel: 'form-cancel',
		delete: 'form-delete',
		name: 'form-name',
		email: 'form-email',
		memberId: 'form-memberId',
		price: 'form-price',
		color: 'form-color',
		icon: 'form-icon',
		description: 'form-description',
		code: 'form-code',
		symbol: 'form-symbol',
		oldPassword: 'form-oldPassword',
		newPassword: 'form-newPassword',
	},
	pos: {
		total: 'sale-summary-total',
		totalLeft: 'sale-summary-total-left',
		submit: 'sale-submit',
		clear: 'sale-clear',
		overdraft: 'sale-overdraft-warning',
		basketRemove: 'basket-item-remove',
		goodsTile: (id: number) => `goods-tile-${id}`,
		basketItem: (id: number) => `basket-item-${id}`,
		filter: (typeId: number) => `filter-panel-${typeId}`,
		reorderToggle: 'reorder-toggle',
		reorderOverlay: 'reorder-overlay',
		reorderExit: 'reorder-exit',
	},
	dialog: {
		confirmYes: 'confirm-yes',
		confirmNo: 'confirm-no',
		chargeAmount: 'charge-amount',
		chargeSubmit: 'charge-submit',
		dischargeAmount: 'discharge-amount',
		dischargeSubmit: 'discharge-submit',
		stornoConfirm: 'storno-confirm',
		assignCardSubmit: 'assign-card-submit',
	},
	cardInfo: {
		balance: 'card-info-balance',
		qr: 'card-info-qr',
		group: (id: number) => `card-info-group-${id}`,
	},
	checkIn: {
		memberId: 'checkin-member-id',
		name: 'checkin-name',
		email: 'checkin-email',
		group: 'checkin-group',
		submit: 'checkin-submit',
		reset: 'checkin-reset',
		search: 'checkin-search',
		userResult: (id: number) => `checkin-user-${id}`,
		deposit: 'checkin-deposit',
	},
	placeSelect: {
		option: (id: number) => `place-option-${id}`,
	},
	userInfo: {
		search: 'user-info-search',
		userOption: (id: number) => `user-info-option-${id}`,
		memberId: 'member-id',
		groupChip: (id: number) => `profile-group-chip-${id}`,
		groupRemove: (id: number) => `profile-group-remove-${id}`,
		groupSelect: 'profile-group-select',
		groupAddBtn: 'profile-group-add-btn',
	},
	tx: {
		tabAll: 'tx-tab-all',
		tabPlace: 'tx-tab-place',
		tabUser: 'tx-tab-user',
		row: (id: number) => `tx-row-${id}`,
		storno: 'tx-row-storno-btn',
		filterFrom: 'tx-filter-from',
		filterTo: 'tx-filter-to',
	},
	row: {
		user: (id: number) => `row-user-${id}`,
		place: (id: number) => `row-place-${id}`,
		goods: (id: number) => `row-goods-${id}`,
		currency: (id: number) => `row-currency-${id}`,
		group: (id: number) => `row-group-${id}`,
		actionEdit: 'row-action-edit',
		actionDelete: 'row-action-delete',
		actionChangePassword: 'row-action-change-password',
	},
} as const;

export const ALERT = {
	success: '.mat-mdc-snack-bar-container.alert-success',
	error: '.mat-mdc-snack-bar-container.alert-error',
	info: '.mat-mdc-snack-bar-container.alert-info',
} as const;
