export enum ERoute {
	LOGIN = 'login',
	LOGIN_SIGN_IN = 'sign-in',
	PLACE_SELECT = 'place-select',
	SALE = 'sale',
	ADMIN = 'admin',
	ADMIN_USERS = 'users',
	ADMIN_PLACES = 'places',
	ADMIN_GOODS = 'goods',
	ADMIN_GOODS_TYPES = 'types',
	ADMIN_CURRENCIES = 'currencies',
	ADMIN_CHARGE = 'charge',
	ADMIN_TRANSACTIONS = 'transactions',
	EDIT = 'edit',
	NEW = 'new',
}
