export enum ERoute {
	LOGIN = 'login',
	LOGIN_SIGN_IN = 'sign-in',
	PLACE_SELECT = 'place-select',
	CHECK_IN = 'check-in',
	SALE = 'sale',
	ADMIN = 'admin',
	ADMIN_USERS = 'users',
	ADMIN_PLACES = 'places',
	ADMIN_GOODS = 'goods',
	ADMIN_GOODS_TYPES = 'types',
	ADMIN_CURRENCIES = 'currencies',
	ADMIN_CHARGE = 'charge',
	ADMIN_TRANSACTIONS = 'transactions',
	ADMIN_CHANGE_PASSWORD = 'change-password',
	CARD_INFO = 'card-info',
	EDIT = 'edit',
	NEW = 'new',
}
